FROM envoyproxy/envoy:v1.33.0

WORKDIR /app

COPY requirements.txt .
COPY src/ ./src/

ENV APP_NAME=docker-python \
    APP_ENV=production \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1

CMD ["envoy", "--version"]
